"""Canonical pool of composers to rank by pageviews and sample from.

These are Wikipedia article titles (English). Add/remove names freely — the seed
script will random-sample from the top-N of this list by recent pageviews.
"""

CANDIDATE_COMPOSERS: list[str] = [
    # Medieval / Renaissance
    "Hildegard of Bingen", "Guillaume de Machaut", "Josquin des Prez",
    "Thomas Tallis", "William Byrd", "Giovanni Pierluigi da Palestrina",
    "Orlande de Lassus", "John Dunstaple", "Guillaume Dufay",
    "Johannes Ockeghem", "Carlo Gesualdo", "Tomás Luis de Victoria",
    "John Taverner", "Jacob Obrecht", "Heinrich Isaac",
    # Baroque
    "Johann Sebastian Bach", "George Frideric Handel", "Antonio Vivaldi",
    "Henry Purcell", "Jean-Baptiste Lully", "Jean-Philippe Rameau",
    "Georg Philipp Telemann", "Domenico Scarlatti", "Arcangelo Corelli",
    "Tomaso Albinoni", "Claudio Monteverdi", "Heinrich Schütz",
    "Alessandro Scarlatti", "Dieterich Buxtehude", "Johann Pachelbel",
    "Barbara Strozzi", "Francesca Caccini", "François Couperin",
    "Marc-Antoine Charpentier", "Carl Philipp Emanuel Bach",
    "Johann Christian Bach", "Wilhelm Friedemann Bach", "Girolamo Frescobaldi",
    "Jean-Féry Rebel", "Élisabeth Jacquet de La Guerre",
    # Classical
    "Wolfgang Amadeus Mozart", "Ludwig van Beethoven", "Joseph Haydn",
    "Michael Haydn", "Muzio Clementi", "Luigi Boccherini",
    "Christoph Willibald Gluck", "Antonio Salieri", "Johann Nepomuk Hummel",
    "Maria Theresia von Paradis", "Luigi Cherubini", "Giovanni Battista Viotti",
    "Étienne Méhul", "Carl Stamitz", "Johann Stamitz",
    # Romantic
    "Franz Schubert", "Hector Berlioz", "Felix Mendelssohn",
    "Fanny Mendelssohn", "Frédéric Chopin", "Robert Schumann",
    "Clara Schumann", "Franz Liszt", "Richard Wagner", "Giuseppe Verdi",
    "Johannes Brahms", "Anton Bruckner", "Gustav Mahler",
    "Richard Strauss", "Hugo Wolf", "Pyotr Ilyich Tchaikovsky",
    "Nikolai Rimsky-Korsakov", "Modest Mussorgsky", "Alexander Borodin",
    "Mily Balakirev", "César Cui", "Mikhail Glinka", "Anton Rubinstein",
    "Antonín Dvořák", "Bedřich Smetana", "Edvard Grieg", "Jean Sibelius",
    "Edward Elgar", "Ralph Vaughan Williams", "Camille Saint-Saëns",
    "Gabriel Fauré", "César Franck", "Jules Massenet", "Charles Gounod",
    "Georges Bizet", "Giacomo Puccini", "Gioachino Rossini",
    "Vincenzo Bellini", "Gaetano Donizetti", "Carl Maria von Weber",
    "Niccolò Paganini", "Pablo de Sarasate", "Henryk Wieniawski",
    "Joseph Joachim", "Amy Beach", "Cécile Chaminade", "Louise Farrenc",
    "Ethel Smyth", "Mel Bonis", "Alkan", "Mikalojus Konstantinas Čiurlionis",
    # Late Romantic / early 20th
    "Claude Debussy", "Maurice Ravel", "Erik Satie", "Igor Stravinsky",
    "Sergei Rachmaninoff", "Alexander Scriabin", "Sergei Prokofiev",
    "Dmitri Shostakovich", "Aram Khachaturian", "Nikolai Medtner",
    "Leoš Janáček", "Béla Bartók", "Zoltán Kodály", "Karol Szymanowski",
    "Carl Nielsen", "Arnold Schoenberg", "Alban Berg", "Anton Webern",
    "Paul Hindemith", "Kurt Weill", "Ferruccio Busoni", "Ernest Bloch",
    "Lili Boulanger", "Nadia Boulanger", "Germaine Tailleferre",
    "Francis Poulenc", "Darius Milhaud", "Arthur Honegger",
    "Manuel de Falla", "Isaac Albéniz", "Enrique Granados",
    "Heitor Villa-Lobos", "Ottorino Respighi", "Ferde Grofé",
    "Florence Price", "William Grant Still", "Margaret Bonds",
    # Mid-to-late 20th century
    "Olivier Messiaen", "Pierre Boulez", "Karlheinz Stockhausen",
    "Luciano Berio", "Luigi Nono", "Bruno Maderna", "Iannis Xenakis",
    "György Ligeti", "György Kurtág", "Witold Lutosławski",
    "Krzysztof Penderecki", "Henryk Górecki", "Alfred Schnittke",
    "Sofia Gubaidulina", "Arvo Pärt", "John Cage", "Morton Feldman",
    "Earle Brown", "Christian Wolff (composer)", "Henry Cowell",
    "Conlon Nancarrow", "Lou Harrison", "Harry Partch", "Charles Ives",
    "Aaron Copland", "Samuel Barber", "Leonard Bernstein",
    "George Gershwin", "Virgil Thomson", "Elliott Carter",
    "Milton Babbitt", "Roger Sessions", "Walter Piston",
    "Howard Hanson", "William Schuman", "Alan Hovhaness",
    "John Adams (composer)", "Philip Glass", "Steve Reich",
    "Terry Riley", "La Monte Young", "Pauline Oliveros",
    "Meredith Monk", "Joan Tower", "Ellen Taaffe Zwilich",
    "Jennifer Higdon", "Libby Larsen", "Julia Wolfe", "Missy Mazzoli",
    "Caroline Shaw", "Nico Muhly", "Max Richter", "Jóhann Jóhannsson",
    "Benjamin Britten", "Michael Tippett", "William Walton",
    "Peter Maxwell Davies", "Harrison Birtwistle", "Thomas Adès",
    "James MacMillan", "George Benjamin (composer)", "Judith Weir",
    "Rebecca Saunders", "Unsuk Chin", "Tōru Takemitsu",
    "Toshio Hosokawa", "Tan Dun", "Bright Sheng", "Kaija Saariaho",
    "Magnus Lindberg", "Esa-Pekka Salonen", "Einojuhani Rautavaara",
    "Osvaldo Golijov", "Tania León", "George Crumb",
    "Charles Wuorinen", "Jacob Druckman", "Ned Rorem",
    # Music Restored — suppressed by Nazi regime
    "Walter Braunfels", "Hanns Eisler", "Veniamin Fleishman",
    "Hans Gál", "Berthold Goldschmidt", "Pavel Haas",
    "Karl Amadeus Hartmann", "Jaroslav Ježek", "Vítězslava Kaprálová",
    "Gideon Klein", "Erich Wolfgang Korngold", "Hans Krása",
    "Ernst Krenek", "Bohuslav Martinů", "Franz Reizenstein",
    "Franz Schreker", "Erwin Schulhoff", "Marcel Tyberg",
    "Viktor Ullmann", "Mieczysław Weinberg",
    "Jaromír Weinberger", "Eric Zeisl", "Alexander von Zemlinsky",
    # Underrepresented — women composers
    "Hildegard von Bingen", "Kassia", "Isabella Leonarda",
    "Elisabeth-Claude Jacquet de la Guerre", "Marianna Martines",
    "Maria Theresia von Paradis", "Emilie Mayer", "Augusta Holmès",
    "Alma Mahler", "Rebecca Clarke", "Ruth Crawford Seeger",
    "Grażyna Bacewicz", "Galina Ustvolskaya", "Younghi Pagh-Paan",
    "Gloria Coates", "Chen Yi", "Judith Bingham",
    "Augusta Read Thomas", "Olga Neuwirth", "Anna Thorvaldsdottir",
    "Du Yun", "Dai Fujikura",
    # Underrepresented — composers of color
    "Chevalier de Saint-Georges", "Samuel Coleridge-Taylor",
    "Nathaniel Dett", "Ulysses Kay", "George Walker (composer)",
    "Coleridge-Taylor Perkinson", "Julius Eastman", "Adolphus Hailstork",
    "T. J. Anderson", "Alvin Singleton", "Jeffrey Mumford",
    "Michael Abels", "Jessie Montgomery", "Carlos Simon",
    "Valerie Coleman", "Joel Thompson", "Errollyn Wallen",
    "Eleanor Alberga", "José White Lafitte", "Amadeo Roldán",
    "Silvestre Revueltas", "Carlos Chávez", "Alberto Ginastera",
    "Astor Piazzolla", "Akira Ifukube", "Isang Yun",
    "José Maurício Nunes Garcia",
    # Donne UK — historical women composers
    "Chiara Margarita Cozzolani", "Rosa Giacinta Badalla",
    "Antonia Bembo", "Camilla de Rossi",
    "Marianna von Martines", "Maria Anna Mozart",
    "Maria Theresia von Paradis", "Hélène de Montgeroult",
    "Corona Schröter", "Josepha Barbara Auenbrugger",
    "Amélie-Julie Candeille", "Sophie Gail",
    "Annette von Droste-Hülshoff", "Bettina von Arnim",
    "Hortense de Beauharnais", "Pauline Duchambge",
    "Maria Szymanowska", "Josephine Lang",
    "Pauline Viardot", "Ingeborg von Bronsart",
    "Agathe Backer Grøndahl", "Dora Pejačević",
    "Nadia Judd", "Morfydd Llwyn Owen",
    "Elizabeth Maconchy", "Priaulx Rainier",
    "Peggy Glanville-Hicks", "Grazyna Bacewicz",
    "Thea Musgrave", "Betsy Jolas",
]
